In [1]:
import pandas as pd

In [2]:
import pandas as pd

# Load the saved CSV
df = pd.read_csv('../data/crypto_exchange_data.csv')
df

,Text,Reddit Score,Date,Source,Exchange,Sentiment,Platform,Rating
0,"Binance is a exchange, think of it as a bank o...",2.0,2021-05-01,r/CryptoCurrency,binance,negative,web,NaN
1,"Finally, they are doing something about him. T...",-3.0,2021-02-26,r/CryptoCurrency,crypto.com,negative,web,NaN
2,"God I hope not. \n\n""Good morning user , you u...",13.0,2021-05-18,r/CryptoCurrency,crypto.com,negative,web,NaN
3,I disagree. I think gamers have some of the lo...,3.0,2021-12-20,r/CryptoCurrency,crypto.com,negative,web,NaN
4,Or should have given compensation to others wh...,167.0,2022-08-30,r/CryptoCurrency,crypto.com,negative,web,NaN
...,...,...,...,...,...,...,...,...
125692,I am not sure what your comment is implying. ...,1.0,2021-04-24,r/Ethereum,general,positive,web,NaN
125693,Why would anyone want to do that. What if the ...,1.0,2021-08-04,r/Ethereum,general,positive,web,NaN
125694,Especially since Doge has seen prices nearly 1...,6.0,2021-04-23,r/Ethereum,general,positive,web,NaN
125695,Someone will fill this gap up so fast,1.0,2021-08-20,r/Ethereum,general,positive,web,NaN
125696,This post seems to completely ignore all the d...,1.0,2021-05-07,r/Ethereum,general,positive,web,NaN

In [3]:
# Total number of records
num_records = len(df)

# Total number of words
word_counts = df['Text'].str.split().str.len()
total_words = word_counts.sum()

# Total number of unique words (types)
all_words = ' '.join(df['Text']).split()
unique_words = set(all_words)
num_unique_words = len(unique_words)

# General vs Exchange-specific stats
is_general = df['Exchange'] == 'general'
general_records = df[is_general]
exchange_records = df[~is_general]

general_stats = {
    'Records': len(general_records),
    'Words': general_records['Text'].str.split().str.len().sum(),
    'Unique Words': len(set(' '.join(general_records['Text']).split()))
}

exchange_stats = {
    'Records': len(exchange_records),
    'Words': exchange_records['Text'].str.split().str.len().sum(),
    'Unique Words': len(set(' '.join(exchange_records['Text']).split()))
}

# Create DataFrames for display
overall_stats_df = pd.DataFrame([{
    'Records': num_records,
    'Words': total_words,
    'Unique Words': num_unique_words
}])

general_vs_exchange_df = pd.DataFrame([
    {'Type': 'General', **general_stats},
    {'Type': 'Exchange', **exchange_stats}
])

In [4]:
# Overall Corpus Statistics
overall_stats_df

   Records    Words  Unique Words
0   125697  3884026        173143

In [5]:
# General vs Exchange Statistics
general_vs_exchange_df

       Type  Records    Words  Unique Words
0   General   111750  3130355        147735
1  Exchange    13947   753671         57729

We can observe that the combined and even the individual (general and exchange) data, meet our 3 main requirements:
1. Corpus to have at least 10,000 records
2. Corpus to have at least 100,000 words
3. Balanced data